### ISSUE TITLE
After updating from 0.9.32 to 0.9.33 I've started getting exceptions on components

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#111] opened 2024-09-02 00:01 UTC
Just updated to 0.9.33 and I'm getting this exception on code that was working fine with 0.9.32:

Traceback (most recent call last):
  File "C:\test\venv\lib\site-packages\django\template\base.py", line 835, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "C:\test\venv\lib\site-packages\django\utils\functional.py", line 231, in wrapper
    return func(*args, **kwargs)
  File "C:\test\venv\lib\site-packages\django\utils\text.py", line 446, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: ''

It seems like if one of my template tag strings is empty that's when this occurs.  I'll see if I can repro it with a simple project.

**Comment by ra-dave** [comment] 2024-09-02 00:14
Here's a simple repro:

views.py
`return render(request, 'test.html', {'test_string_from_view': ''})`

my_component.html
`{{ test_string }}`

home.html
` <c-my-component test_string="{{ test_string_from_view }}" />`

If test_string_from_view is empty then the exception occurs. If the string is not empty it works as expected.

**Comment by wrabit** [comment] 2024-09-02 07:25
@ra-dave Thanks for the report and reproducible snippet, an additional exception needed handling, now handled and tested in #112, fixed in latest release, v0.9.34

**Closed as completed by wrabit** 2024-09-02 07:25 UTC

**Comment by ra-dave** [comment] 2024-09-02 12:09
Trying 0.9.34.  While the exception that was happening in 0.9.33 has gone away, now certain values being returned from my view are getting mangled.  For example, `return render(request, 'test.html', {'test_string_from_view': '1,234'})` will display (1, 234) on the page rather than 1,234

Also, returning a blank string from the view `return render(request, 'test.html', {'test_string_from_view': ''})` now results in "True" being displayed on the page

**Comment by wrabit** [comment] 2024-09-02 15:56
@ra-dave thanks for reporting, I will expand the test coverage in this area and look to resolve soon.

**Comment by wrabit** [comment] 2024-09-02 21:27
@ra-dave the peculiar numbering issue is from incorrect evaluation of a non-dynamic attribute - it's been fixed in v0.9.35. 

The other issue where boolean True is being generated from a `=""` is something that existed for some time now due to compilation constraints. I have started work on resolving this.
