### ISSUE TITLE
Cotton startup adds many seconds to a page render when it has to compile components

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#165] opened 2024-09-26 05:46 UTC
I have a web page with around 70 components.  The first time I visit the page it takes about 7800ms for the page to come up.  After that it takes about 140ms.  It appears the majority of the time for the first view is being spent in cotton.

For example, this section of the profiling alone is taking almost 4 seconds (the numbers are cumulative time):

6.852    /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:31(get_contents)
6.849    /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:115(process)
4.525    /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:189(_compile_cotton_to_django)
4.298    /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:254(_transform_components)
2.947    /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:321(_make_soup)

I can probably live with this if this is a one-time delay at my site's startup but this just seems excessively long.  After the initial delay the pages do load quickly but every once in awhile there is the odd refresh where it takes several seconds again.  Not sure if this is a cotton delay or not though, I need to do some more profiling.   Any chance cotton could be invalidating the cache for some reason?

**Comment by wrabit** [comment] 2024-09-26 06:35
@ra-dave could you paste your settings file? `TEMPLATES` section and also how you are installing cotton (using `django_cotton` or `django_cotton.apps.SimpleAppConfig` in `INSTALLED_APPS`).

Cotton relies on Django's cached loader being present for optimal performance. Without it, cotton has it's own mechanism which is slightly less performant. Both caches should exists for the runtime of the Django app (it's reset between deployments / server restarts). If you could catch profiling for the slow loads that you mention happening after the initial load, that would be useful to see the files causing that.

**Comment by ra-dave** [comment] 2024-09-26 17:11
Using 'django_cotton' in INSTALLED_APPS.

```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [ BASE_DIR / 'templates', BASE_DIR / 'venv/Lib/site-packages/tailwind/templates', BASE_DIR / 'venv/Lib/site-packages/meta/templates' ],
        'APP_DIRS': False,
        "OPTIONS": {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }
    }
]
```

Here's a profile of a slow load after initial startup.   It does seem like cotton is recompiling:

       16    0.000    0.000    3.983    0.249 /opt/render/project/src/.venv/lib/python3.11/site-packages/django/template/loaders/cached.py:25(get_contents)
       16    0.000    0.000    3.983    0.249 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:31(get_contents)
        2    0.000    0.000    3.980    1.990 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:115(process)
        2    0.000    0.000    2.702    1.351 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:189(_compile_cotton_to_django)
    221/2    0.025    0.000    2.535    1.268 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:254(_transform_components)
     1445    0.010    0.000    1.789    0.001 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:321(_make_soup)
     1445    0.026    0.000    1.756    0.001 /opt/render/project/src/.venv/lib/python3.11/site-packages/bs4/__init__.py:122(__init__)
     1445    0.007    0.000    1.656    0.001 /opt/render/project/src/.venv/lib/python3.11/site-packages/bs4/__init__.py:471(_feed)
     1445    0.006    0.000    1.618    0.001 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/utils.py:88(feed)
     2890    0.142    0.000    1.594    0.001 /usr/local/lib/python3.11/html/parser.py:133(goahead)
     1445    0.003    0.000    1.594    0.001 /usr/local/lib/python3.11/html/parser.py:103(feed)
        2    0.003    0.001    1.255    0.627 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/cotton_loader.py:200(_replace_placeholders_with_syntax)
      242    0.007    0.000    1.253    0.005 /usr/local/lib/python3.11/re/__init__.py:178(sub)
      343    1.158    0.003    1.159    0.003 {method 'sub' of 're.Pattern' objects}
     8075    0.150    0.000    0.927    0.000 /usr/local/lib/python3.11/html/parser.py:300(parse_starttag)
     8075    0.052    0.000    0.613    0.000 /opt/render/project/src/.venv/lib/python3.11/site-packages/django_cotton/utils.py:51(handle_starttag)

Oddly, this only seems to happen a few times and then it settles down and doesn't happen again until I restart the website.  For example, here are separate page loads (the initial page load after startup is on the right):

![image](https://github.com/user-attachments/assets/4aa2f341-459e-4ae2-ac46-eaebe13bd17c)

**Comment by alfonsrv** [comment] 2024-09-26 21:41
The re-compile happening a few times is in-line with the multiple reloads I observed using https://github.com/adamchainz/django-browser-reload since I added django-cotton.

While I love this library and its abstraction, it really slows down development having to wait 30 seconds for every component change to settle until django-cotton settles.

**Comment by wrabit** [comment] 2024-09-26 22:12
@ra-dave @alfonsrv I run on several projects without performance issues but if you are able to provide a reproducible or a private copy of your project Id like to be able to take a closer look..

**Comment by ra-dave** [comment] 2024-09-26 23:16
Most of my components make extensive use of htmx, perhaps that makes it slow to compile?  Still don't understand why the cache would be expiring though.

Unfortunately I have other battles to fight at the moment so I can't spend anymore time on this.

**Comment by wrabit** [comment] 2024-09-27 10:21
> Using 'django_cotton' in INSTALLED_APPS.

@ra-dave can I ask what else you have installed? One thing I would look at if any other plugin has something that adjusts the loaders, maybe bypassing the cache loader changing loader config structure.

**Comment by g-nie** [comment] 2024-09-27 10:39
> The re-compile happening a few times is in-line with the multiple reloads I observed using https://github.com/adamchainz/django-browser-reload since I added django-cotton.
> 
> While I love this library and its abstraction, it really slows down development having to wait 30 seconds for every component change to settle until django-cotton settles.

Hey. I am also experiencing this. My setup is `django-cotton`, `django-tailwind`, `django-template-partials` (using the loaders from the docs: https://django-cotton.com/docs/django-template-partials) and `django-browser-reload`, and it all runs on Docker. It seems to work perfectly fine when starting with fresh containers but things really do slow down after _some*_ page refreshes/automatic refreshes from the browser-reload package. My guess would be that this is a dev-environment only thing.

*I haven't been able to identify the cause yet, I should have some more free time on the weekend, hopefully I can provide more info.

**Comment by wrabit** [comment] 2024-09-27 10:57
Thanks @g-nie, when you say “browser reload package” are you referring to the same one @alfonsrv uses?

**Comment by g-nie** [comment] 2024-09-27 11:08
> Thanks @g-nie, when you say “browser reload package” are you referring to the same one @alfonsrv uses?

Yep [this one](https://github.com/adamchainz/django-browser-reload)

**Comment by g-nie** [comment] 2024-09-27 13:24
Ok here's a minimal-ish demo that hopefully illustrates the issue https://github.com/g-nie/cotton-reload. Instructions in the README

**Comment by ra-dave** [comment] 2024-09-27 17:51
> > Using 'django_cotton' in INSTALLED_APPS.
> 
> @ra-dave can I ask what else you have installed? One thing I would look at if any other plugin has something that adjusts the loaders, maybe bypassing the cache loader changing loader config structure.

Here's my apps.  I have not used browser reload for some time due to other reasons.

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'tailwind',
    'theme',
    'meta',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'a_home',
    # 'django_browser_reload',
    'django_cotton',
    'axes',
    # 'silk',
]
```

**Comment by wrabit** [comment] 2024-09-27 18:18
@g-nie thanks for the useful repro, I believe the culprit to be the `get_dirs()` in the loader. Since the results shouldn't change during runtime, caching this method should deal with it, locally for me it resolved the issue.

I will release this soon, hopefully you will be able to try it out and let me know for sure that it resolves the issue for you.

**Comment by wrabit** [comment] 2024-09-27 18:53
An update is released in [1.0.11](https://github.com/wrabit/django-cotton/releases/tag/v1.0.11). Please check it out and let me know if it resolves your issues.

**Comment by alfonsrv** [comment] 2024-09-27 19:39
@wrabit seems to work great now from my quick testing!

fyi with Python 3.8 – `ImportError: cannot import name 'cache' from 'functools' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py)`

**Comment by g-nie** [comment] 2024-09-27 20:26
It's also looking good here @wrabit 👌 Thanks for the super quick release!

Great job on cotton, it's such a useful tool.

**Comment by ra-dave** [comment] 2024-09-27 21:41
I haven't profiled it yet but it's seems faster for me as well.  Thanks for such rapid support!

**Comment by wrabit** [comment] 2024-09-27 22:07
Good to hear @ra-dave. Interestingly enough, it's pushed the [render benchmarks](https://github.com/wrabit/django-cotton/blob/main/dev/example_project/render_load_test.py) to new levels:

```
Average of 5 runs of 500 iterations each 
---
Native Django {% for %} loop: 3.51 ms
Cotton equivalent: 2.89 ms
---
Native {% include %}: 2.98 ms
Cotton equivalent: 2.90 ms
---
Native {% block %} and {% extends %}: 9.29 ms
Cotton equivalent: 10.50 ms
```

(These are simple tests)

@alfonsrv changed @cache to the equivalent @lru_cache(max_size=None) to support python 3.8 in [v1.0.12](https://github.com/wrabit/django-cotton/releases/tag/v1.0.12)

**Closed as completed by wrabit** 2024-09-27 22:07 UTC
